### ISSUE TITLE
Agreeing to draw offer does not end the game for all players

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gnochess#104]
## Description

When player 1 proposes a draw, and player 2 accepts, their draw / resign controls simply disappear, and they are not returned to the homepage
<img width="1440" alt="Screenshot 2023-09-24 at 06 09 11" src="https://github.com/gnolang/gnochess/assets/16712663/b43b5eb8-b5d1-4a12-af2c-c1cac43f3593">

**Comment by alexiscolin** [comment]
I think it's a responsive issue... . The draw final screen should appear but is not displayed because of mobile style I think. Lemme check since this could be an issue with the victory screen as well (they are the same)
