### ISSUE TITLE
Letting the draw request time out without a response, triggers another draw request on the frontend to the original draw proposer

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gnochess#105]
## Description

- player 1 and player 2 are playing the game 
- player 1 proposes a draw 
- player 2 does not answer to this draw request
- player 1 is presented with a draw request on their UI
- player 2s draw request disappears (correct)

ex screen on player 1 (the original draw proposer, second request that was randomly triggered?)
<img width="715" alt="Screenshot 2023-09-24 at 06 14 47" src="https://github.com/gnolang/gnochess/assets/16712663/959b16af-1365-4c23-9986-e9f1e2ee77cb">

**Comment by alexiscolin** [comment]
It may sound harsh but what if we remove these controls option for v1 @zivkovicmilos ? If you want to resign, you leave the page (you cannot go back in the current state) and you let the game engine create a draw for you. But yeah that means, the user can take 100000hours on a loose machine to get that "auto draw" event appears automatically... It may finish as a war of attrition: who will resign bu leaving the game first.

**Comment by zivkovicmilos** [comment]
@thehowl @ajnavarro what do you think?

**Comment by thehowl** [comment]
I'd want to keep them, at the very very least resignation.

On the backend, I can add a checker to verify if the game is eligible for auto-draw (insufficient material, 3-fold, 50-move), and we can enable the button only when it is.

This way we can disable the draw button for draw by agreement, which requires more UI work as far as I can tell.

WDYT?

**Comment by alexiscolin** [comment]
So just to be sure: we could remove the `draw` button but we should keep the `resign` one?

**Comment by thehowl** [comment]
@alexiscolin yes!

**Comment by alexiscolin** [comment]
Resign is OK I'm gonna try to keep the draw button.
