### ISSUE TITLE
Frontend: timout game over not send to server after it reached 0:0

### ISSUE THREAD

**Issue by alexiscolin** [gnolang/gnochess#115]
@thehowl  The server has not returned a `gameover` during the `isGameOngoing` setTimeout function....  For the recall the front is responsible for sending the timeout `gameover` right? 
The `isGameOngoing` that run in a loop (currently, even after the game is finished in the front) only returns a `false` after a final move (a final move **after** the timer reached 0 in the front) . 

It means the timer should be broken and don’t send the info to the server when it reached 0.
_May be related but the white player timer is updated to 01-01 when this `gameover` is dispatched._ 

<img width="1725" alt="Capture d’écran 2023-09-24 à 16 54 31" src="https://github.com/gnolang/gnochess/assets/7622257/af2842c0-0e47-4f8b-a3d8-f62fe2774f4f">

**Comment by ajnavarro** [comment]
We are not calling `ClaimTimeout(gameID string)` when one of the players believes that we reached a timeout.
