### ISSUE TITLE
Frontend: 30 seconds rule is also applied to black first move

### ISSUE THREAD

**Issue by ajnavarro** [gnolang/gnochess#139]
30 seconds rule must be only applied to the first white move.

**Comment by alexiscolin** [comment]
I don't see any 30s rule on the second white move. The timer doesn't start at the white second move on your computer?

**Comment by thehowl** [comment]
>30 seconds rule must be only applied to the first white move.

nono it's both black and white

**Comment by ajnavarro** [comment]
ok closing it
