### ISSUE TITLE
Frontend grammar fixes

### ISSUE THREAD

**Issue by thehowl** [gnolang/gnochess#62]

**Comment by leohhhn** [comment]
Errors I noticed yesterday were already fixed and merged in [PR#58](https://github.com/gnolang/gnochess/pull/58). Currently cannot get past the opponent searching screen but everything else checks out grammar-wise.

**Comment by thehowl** [comment]
@leohhhn What say you about reviewing the HTML files under `web/layouts`?

Most typos are bound to be there.

**Comment by leohhhn** [comment]
@thehowl went through all subfolders. PR [here](https://github.com/gnolang/gnochess/pull/67)
